name: Run Tests and Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6]
        django-version: [1.11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -q Django==${{ matrix.django-version }}
          pip install -e .[flake8,tests]

      - name: Lint with flake8
        run: flake8

      - name: Test with pytest
        run: pytest
